services:
  executrollgram:
    image: ghcr.io/cloudaxdm/executrollgram:latest
    environment:
      BOT_TOKEN: "tu_token_de_telegram"
      SCRIPTS_DIR: /app/scripts
      ALLOWED_CHAT_IDS: "tu_chat_id"
      SCRIPT_TIMEOUT_SECONDS: "60"
      MAX_OUTPUT_CHARS: "3500"
    volumes:
      - ./scripts:/app/scripts:ro
    restart: unless-stopped
